new-item -path C:\ -name "Prohibited Media Files" -type directory
new-item -path "C:\Prohibited Media Files" -name "Files to delete.txt" -type "file"
Get-ChildItem C:\Users\ -force -filter *.mp3 -Recurse -ErrorAction SilentlyContinue | Out-File -append "C:\Prohibited Media Files\Files to delete.txt"
Get-ChildItem C:\Users\ -force -filter *.mp4 -Recurse -ErrorAction SilentlyContinue | Out-File -append "C:\Prohibited Media Files\Files to delete.txt"
Get-ChildItem C:\Users\ -force -filter *.avi -Recurse -ErrorAction SilentlyContinue | Out-File -append "C:\Prohibited Media Files\Files to delete.txt"
Get-ChildItem C:\Users\ -force -filter *.mov -Recurse -ErrorAction SilentlyContinue | Out-File -append "C:\Prohibited Media Files\Files to delete.txt"
Get-ChildItem C:\Users\ -force -filter *.jpg -Recurse -ErrorAction SilentlyContinue | Out-File -append "C:\Prohibited Media Files\Files to delete.txt"
Get-ChildItem C:\Users\ -force -filter *.gif -Recurse -ErrorAction SilentlyContinue | Out-File -append "C:\Prohibited Media Files\Files to delete.txt"
Get-ChildItem C:\Users\ -force -filter *.wav -Recurse -ErrorAction SilentlyContinue | Out-File -append "C:\Prohibited Media Files\Files to delete.txt"
Get-ChildItem C:\Users\ -force -filter *.png -Recurse -ErrorAction SilentlyContinue | Out-File -append "C:\Prohibited Media Files\Files to delete.txt"
Get-ChildItem C:\Users\ -force -filter *.txt -Recurse -ErrorAction SilentlyContinue | Out-File -append "C:\Prohibited Media Files\Files to delete.txt"
Get-ChildItem C:\ -force -filter "*backdoor*" -Recurse -ErrorAction SilentlyContinue | Out-File -append "C:\Prohibited Media Files\Files to delete.txt"
Get-ChildItem C:\ -force -filter "*malicious*" -Recurse -ErrorAction SilentlyContinue | Out-File -append "C:\Prohibited Media Files\Files to delete.txt"
Get-ChildItem C:\ -force -filter "*trojan*" -Recurse -ErrorAction SilentlyContinue | Out-File -append "C:\Prohibited Media Files\Files to delete.txt"
Get-ChildItem C:\ -force -filter "*horse*" -Recurse -ErrorAction SilentlyContinue | Out-File -append "C:\Prohibited Media Files\Files to delete.txt"
Get-ChildItem C:\ -force -filter "*hack*" -Recurse -ErrorAction SilentlyContinue | Out-File -append "C:\Prohibited Media Files\Files to delete.txt"
